CREATE TABLE IF NOT EXISTS public."Benign"
(
    "No." bigint,
    "Time" double precision,
    "SrcIP" character varying,
    "DstIP" character varying,
    "Protocol" character varying,
    "Length" bigint,
    "Info" text,
    "SrcMAC" character varying,
    "SrcMACResolved" character varying,
    "SrcOUIResolved" character varying,
    "SrcPort" double precision,
    "SequenceNumber" double precision,
    "SrcOUI" character varying,
    "DstMAC" character varying,
    "DstMACResolved" character varying,
    "DstOUI" character varying,
    "DstOUResolved" character varying,
    "DstPort" double precision,
    "DstMACResolved.1" character varying,
    "SYNFlag" character varying,
    "ACKFlag" character varying,
    "ProtocolType" character varying,
    "EpochTime" double precision,
    "RelativeTime" double precision,
    "TimeDelta" double precision,
    "CaptureName" character varying,
    "AttackName" character varying,
    date_time time with time zone
);

CREATE TABLE IF NOT EXISTS public."Mitm"
(
    "No." bigint,
    "Time" double precision,
    "SrcIP" character varying,
    "DstIP" character varying,
    "Protocol" character varying,
    "Length" bigint,
    "Info" text,
    "SrcMAC" character varying,
    "SrcMACResolved" character varying,
    "SrcOUIResolved" character varying,
    "SrcPort" double precision,
    "SequenceNumber" double precision,
    "SrcOUI" character varying,
    "DstMAC" character varying,
    "DstMACResolved" character varying,
    "DstOUI" character varying,
    "DstOUResolved" character varying,
    "DstPort" double precision,
    "DstMACResolved.1" character varying,
    "SYNFlag" character varying,
    "ACKFlag" character varying,
    "ProtocolType" character varying,
    "EpochTime" double precision,
    "RelativeTime" double precision,
    "TimeDelta" double precision,
    "CaptureName" character varying,
    "AttackName" character varying,
    date_time time with time zone
);

CREATE TABLE IF NOT EXISTS public."ModbusQuery2Flooding"
(
    "No." bigint,
    "Time" double precision,
    "SrcIP" character varying,
    "DstIP" character varying,
    "Protocol" character varying,
    "Length" bigint,
    "Info" text,
    "SrcMAC" character varying,
    "SrcMACResolved" character varying,
    "SrcOUIResolved" character varying,
    "SrcPort" double precision,
    "SequenceNumber" double precision,
    "SrcOUI" character varying,
    "DstMAC" character varying,
    "DstMACResolved" character varying,
    "DstOUI" character varying,
    "DstOUResolved" character varying,
    "DstPort" double precision,
    "DstMACResolved.1" character varying,
    "SYNFlag" character varying,
    "ACKFlag" character varying,
    "ProtocolType" character varying,
    "EpochTime" double precision,
    "RelativeTime" double precision,
    "TimeDelta" double precision,
    "CaptureName" character varying,
    "AttackName" character varying,
    date_time time with time zone
);

CREATE TABLE IF NOT EXISTS public."ModbusQueryFlooding"
(
    "No." bigint,
    "Time" double precision,
    "SrcIP" character varying,
    "DstIP" character varying,
    "Protocol" character varying,
    "Length" bigint,
    "Info" text,
    "SrcMAC" character varying,
    "SrcMACResolved" character varying,
    "SrcOUIResolved" character varying,
    "SrcPort" double precision,
    "SequenceNumber" double precision,
    "SrcOUI" character varying,
    "DstMAC" character varying,
    "DstMACResolved" character varying,
    "DstOUI" character varying,
    "DstOUResolved" character varying,
    "DstPort" double precision,
    "DstMACResolved.1" character varying,
    "SYNFlag" character varying,
    "ACKFlag" character varying,
    "ProtocolType" character varying,
    "EpochTime" double precision,
    "RelativeTime" double precision,
    "TimeDelta" double precision,
    "CaptureName" character varying,
    "AttackName" character varying,
    date_time time with time zone
);


CREATE TABLE IF NOT EXISTS public."PingFloodDDos"
(
    "No." bigint,
    "Time" double precision,
    "SrcIP" character varying,
    "DstIP" character varying,
    "Protocol" character varying,
    "Length" bigint,
    "Info" text,
    "SrcMAC" character varying,
    "SrcMACResolved" character varying,
    "SrcOUIResolved" character varying,
    "SrcPort" double precision,
    "SequenceNumber" double precision,
    "SrcOUI" character varying,
    "DstMAC" character varying,
    "DstMACResolved" character varying,
    "DstOUI" character varying,
    "DstOUResolved" character varying,
    "DstPort" double precision,
    "DstMACResolved.1" character varying,
    "SYNFlag" character varying,
    "ACKFlag" character varying,
    "ProtocolType" character varying,
    "EpochTime" double precision,
    "RelativeTime" double precision,
    "TimeDelta" double precision,
    "CaptureName" character varying,
    "AttackName" character varying,
    date_time time with time zone
);

CREATE TABLE IF NOT EXISTS public."TcpSYNFlood"
(
    "No." bigint,
    "Time" double precision,
    "SrcIP" character varying,
    "DstIP" character varying,
    "Protocol" character varying,
    "Length" bigint,
    "Info" text,
    "SrcMAC" character varying,
    "SrcMACResolved" character varying,
    "SrcOUIResolved" character varying,
    "SrcPort" double precision,
    "SequenceNumber" double precision,
    "SrcOUI" character varying,
    "DstMAC" character varying,
    "DstMACResolved" character varying,
    "DstOUI" character varying,
    "DstOUResolved" character varying,
    "DstPort" double precision,
    "DstMACResolved.1" character varying,
    "SYNFlag" character varying,
    "ACKFlag" character varying,
    "ProtocolType" character varying,
    "EpochTime" double precision,
    "RelativeTime" double precision,
    "TimeDelta" double precision,
    "CaptureName" character varying,
    "AttackName" character varying,
    date_time time with time zone
);
